# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get install python-wxgtk2.8
  # Cython.Distutils is broken on setuptools but not on distribute. We need to
  # install distribute and cython separately to make sure it is picked up
  # thereafter for evey pip incantation
  - pip install distribute
  - pip install Cython>=0.15.1
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - python setup.py test
notifications:
  email: false
