# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get install python-wxgtk2.8
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - python setup.py test
notifications:
  email: false
