# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get install python-wxgtk2.8 python-pyside
  # Cython.Distutils is broken on setuptools but not on distribute. We need to
  # install distribute and cython separately to make sure it is picked up
  # thereafter for evey pip incantation
  - mkdir builds
  - pushd builds
  - deactivate
  - virtualenv --system-site-packages --distribute $PWD/.env;
    source $PWD/.env/bin/activate;
  - popd
  - pip install Cython>=0.15.1
  - pip install -r requirements.txt
install:
  - python setup.py install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - python setup.py test
notifications:
  email: false
